"""Item bank for Problem Check List (PCL) — 12 problem categories.

Each category holds a fixed, numbered list of statement items. A student
selects any items that apply ("boleh memilih lebih dari satu"). Scoring is
purely a count/percentage of items selected per category and overall — no
per-item weighting, matching the paper-based instrument.
"""

PCL_CATEGORIES = [
    {
        'kode': 'kesehatan',
        'nama': 'Masalah Kesehatan',
        'items': [
            'Sering sakit ketika di SD',
            'Sering sakit sekarang',
            'Jantung sering berdebar-debar',
            'Sering keluar keringat dingin',
            'Kesehatan saya sering terganggu',
            'Pernah dioperasi',
            'Merasa terlalu gemuk',
            'Merasa terlalu kurus',
            'Selalu kurang nafsu makan',
            'Saya merasa kurang bahagia karena cacat',
            'Sering kurang/tidak dapat tidur',
            'Merasa lelah dan tidak bersemangat',
            'Makanan kurang memenuhi syarat kesehatan',
            'Sering merasa mengantuk',
            'Penglihatan saya kurang',
            'Saya sering pusing/pening',
            'Pendengaran saya kurang',
            'Saya kalau berbicara gagap (terbata-bata)',
            'Kurang hawa segar (Kurang Olahraga)',
            'Sering gemetar dan keluar keringat',
            'Mudah kaget dan gugup (gemetaran)',
            'Sering pingsan',
            'Tekanan darah terlalu rendah',
            'Tekanan darah terlalu tinggi',
            'Mempunyai penyakit yang tidak sembuh-sembuh',
        ],
    },
    {
        'kode': 'ekonomi',
        'nama': 'Masalah Keadaan Kehidupan Ekonomi',
        'items': [
            'Uang saku saya tidak mencukupi',
            'Kekurangan buku-buku karena tidak mampu membeli',
            'Terpaksa sambil bekerja karena ekonomi tidak cukup',
            'Tidak tahu bagaimana caranya menambah biaya sekolah',
            'Saya sering meminjam uang',
            'Penerangan lampu di rumah kurang cukup',
            'Sering berjalan kaki ke sekolah padahal rumah jauh',
            'Orang tua tidak mempunyai pekerjaan tetap',
            'Uang sekolah saya terlalu tinggi',
            'Terlalu banyak saudara yang harus dibiayai orangtua',
            'Saya tidak pernah mendapat uang saku',
            'Ibu/saudara ikut mencari penghasilan tambahan',
            'Terpaksa sering tidak membayar SPP',
            'Lulus sekolah terpaksa tidak meneruskan ke sekolah lanjutan',
            'Ayah dan ibu tidak hidup bersama',
            'Keluarga saya hidup berantakan',
            'Saya ikut orang lain karena orang tua saya tidak mampu',
            'Orang tua mampu dan saya ingin segala keinginan dicukupi',
            'Saya tidak ingin orang tua terlalu mengekang (tidak memberi kebebasan)',
        ],
    },
    {
        'kode': 'keluarga',
        'nama': 'Masalah Keluarga',
        'items': [
            'Saya adalah anak tunggal',
            'Saya adalah anak pertama',
            'Saya adalah anak terakhir',
            'Saya tidak mempunyai Ayah',
            'Saya tidak mempunyai Ibu',
            'Saya selalu dimanja orang tua/saudara',
            'Saya hidup terpisah dengan Orang tua',
            'Selalu bertengkar dengan kakak/adik',
            'Ayah/ibu pulang kerja malam',
            'Di rumah terlalu sibuk membantu pekerjaan orang tua',
            'Pertengkaran ayah dan ibu mengganggu pikiran saya',
            'Pekerjaan orang tua mengganggu pikiran saya',
            'Orang tua kurang memperhatikan saya',
            'Orang tua mencampuri urusan saya',
            'Sulit menyesuaikan diri dengan ayah',
            'Sulit menyesuaikan diri dengan ibu',
            'Di rumah saya merasa kurang senang',
            'Kehidupan di rumah kurang teratur',
            'Keluarga kami kurang tolong menolong',
        ],
    },
    {
        'kode': 'agama_moral',
        'nama': 'Masalah Agama dan Moral',
        'items': [
            'Tidak bersungguh-sungguh menerima pelajaran',
            'Masih meragukan adanya Tuhan',
            'Sering muncul keinginan berganti agama',
            'Malas beribadah',
            'Tidak bersungguh-sungguh mengerjakan ibadah',
            'Kurang merasakan manfaat agama',
            'Sering berbohong',
            'Sering mengingkari janji',
            'Sering mengakui kesalahan',
            'Sering iri hati',
            'Ucapan dan perbuatan sering tidak sama',
            'Sering mengambil barang orang lain',
            'Sering mempermainkan orang lain',
            'Pernah melanggar kesusilaan (aturan/norma masyarakat)',
            'Kurang menghargai orang yang memiliki agama selain agama saya',
            'Mudah kasihan terhadap penderitaan orang lain',
            'Kurang menghargai orang lain',
            'Sering tidak mengembalikan barang orang lain yang dipinjam',
            'Menghormati orang yang lebih tua (Orangtua, Guru, Kakak kelas)',
            'Merasa hormat dengan wanita',
            'Membenci teman yang punya kelebihan',
            'Ada perasaan senang menceritakan hal yang porno (menunjukkan aurat)',
            'Sangat senang bergaul dengan orang yang agak "nakal"',
            'Kurang senang dengan wanita/pria pendiam',
        ],
    },
    {
        'kode': 'pribadi',
        'nama': 'Masalah Pribadi',
        'items': [
            'Tidak suka bergaul dengan orang yang kedudukannya lebih rendah',
            'Tidak suka bergaul dengan orang yang kedudukannya lebih tinggi',
            'Sering merasa malu dengan teman lawan jenis',
            'Sering merasa iri hati',
            'Sulit mendapat teman',
            'Tidak suka bertamu',
            'Tidak mau menerima tamu',
            'Merasa rendah diri/minder',
            'Sering merasa curiga terhadap orang lain',
            'Bersikap kaku dan tidak toleran',
            'Bersikap sinis dalam bergaul',
            'Sering merasa ingin bunuh diri',
            'Merasa pesimis (tidak punya harapan)',
            'Saya ingin lebih menarik perhatian teman',
        ],
    },
    {
        'kode': 'sosial_organisasi',
        'nama': 'Masalah Hubungan Sosial dan Berorganisasi',
        'items': [
            'Tidak senang bermain dengan kelompok',
            'Sering gagal dalam usaha mencari teman',
            'Sulit mendapatkan teman',
            'Merasa tidak disenangi teman-teman di sekolah',
            'Senang menjadi pusat perhatian',
            'Tidak berminat dalam berorganisasi (OSIS, Pramuka)',
            'Terlalu aktif dalam organisasi (OSIS, Pramuka)',
            'Sulit untuk menyesuaikan diri',
            'Mudah tersinggung',
            'Takut bergaul dengan atasan',
            'Tidak pernah menjadi pemimpin',
            'Tidak pernah menyampaikan suatu pendapat',
            'Pendapat sering tidak sama dengan pendapat orang lain',
            'Sulit menerima kekalahan',
            'Selalu ingin berkuasa dalam pergaulan',
            'Bingung bila berhadapan dengan orang banyak',
            'Mudah merasa malu',
            'Mudah marah',
            'Sering tidak sabar',
            'Sering tidak menepati janji',
            'Tidak dapat menerima kritikan',
            'Bersifat tertutup',
            'Lebih senang menjadi anggota daripada menjadi ketua',
            'Jarang diajak bermain-main bersama oleh teman',
        ],
    },
    {
        'kode': 'hobi_waktu_luang',
        'nama': 'Masalah Hobi dan Penggunaan Waktu Luang',
        'items': [
            'Keinginanku untuk rekreasi selalu terhalang',
            'Gemar melukis tetapi tidak mempunyai alat',
            'Waktu liburan saya belajar',
            'Suka olahraga tetapi tidak ada waktu untuk melakukannya',
            'Lebih suka buku hiburan daripada buku pelajaran',
            'Setiap ada film baru saya tonton',
            'Salah satu keluargaku sering menghalangi hobiku',
            'Kesenangan membaca majalah menghabiskan waktu belajar',
            'Habis waktuku untuk menonton TV',
            'Orang tuaku tidak pernah mengajak rekreasi',
            'Terlalu sering rekreasi ke luar kota',
            'Sebagian besar waktu saya pakai untuk belajar',
            'Waktu banyak terpakai untuk membantu orang tua',
            'Saya tidak bisa menggunakan waktu kosong saya',
            'Waktu luang banyak terpakai untuk hobi',
            'Waktu luang banyak terpakai untuk ngobrol',
            'Waktu banyak terpakai untuk latihan seni',
            'Saya tidak senang rekreasi',
            'Lebih senang di rumah daripada menyalurkan hobi di luar rumah',
        ],
    },
    {
        'kode': 'penyesuaian_sekolah',
        'nama': 'Masalah Penyesuaian Terhadap Sekolah',
        'items': [
            'Sering malas masuk sekolah',
            'Sering meninggalkan pelajaran',
            'Sering membolos',
            'Ingin pindah kelas lain',
            'Ingin pindah sekolah',
            'Sering merasa cemas bila ada ulangan',
            'Bahan pelajaran sulit dikuasai',
            'Ingin menjadi pengurus OSIS tapi tidak terpilih',
            'Ada beberapa pelajaran yang tidak saya sukai',
            'Pelajaran di sekolah ini terlalu membosankan',
            'Merasa kurang dimengerti oleh guru',
            'Peraturan sekolah terlalu menekan',
            'Pribadi dari guru menyebabkan saya tidak memperhatikan pelajaran',
            'Beberapa mata pelajaran saya anggap tidak perlu',
            'Di sekolah tidak dapat memusatkan perhatian',
            'Di dalam kelas saya sering melamun',
            'Sering datang terlambat',
            'Saya sering dibenci oleh teman di sekolah',
            'Seorang teman selalu menjengkelkan saya',
            'Tidak ada teman yang saya sukai untuk belajar bersama',
        ],
    },
    {
        'kode': 'penyesuaian_kurikulum',
        'nama': 'Masalah Penyesuaian Terhadap Kurikulum',
        'items': [
            'Pelajaran di sekolah terlalu berat',
            'Pelajaran di sekolah terlalu mudah',
            'Sulit mendapatkan buku-buku pelajaran',
            'Saya takut jika menghadapi ulangan',
            'Saya tidak suka belajar',
            'Saya mengerti isi buku pelajaran',
            'Saya tidak berminat terhadap buku',
            'Saya sering mendapatkan nilai rendah',
            'Saya tidak senang belajar bersama',
            'Sulit memahami dan mengikuti pelajaran',
            'Sering merasa khawatir jika mendapat giliran maju di kelas',
            'Sering merasa kesulitan dalam mengerjakan PR',
            'Pelajaran yang bersifat hitungan sulit bagi saya',
            'Pelajaran yang bersifat hafalan sulit bagi saya',
            'Merasa malas membaca buku perpustakaan',
        ],
    },
    {
        'kode': 'masa_depan_jabatan',
        'nama': 'Masalah Masa Depan yang Berhubungan dengan Jabatan',
        'items': [
            'Saya tidak tahu akan melanjutkan kemana setelah SMP',
            'Sulit mendapatkan pilihan sekolah lanjutan setelah SMP',
            'Khawatir tidak diterima di SMA negeri',
            'Ingin melanjutkan ke jenjang yang lebih tinggi tapi tidak ada biaya',
            'Merasa putus asa dengan masa depan karena sulit mencari pekerjaan',
            'Khawatir nantinya tidak bisa mandiri',
            'Ingin mengetahui bakat dan kemampuan diri',
            'Cita-cita saya tidak sesuai dengan kemampuan diri',
            'Bingung menentukan sikap setelah lulus nanti',
            'Merasa bingung jika belum bekerja',
            'Sering berdebar jika mengingat masa depan',
            'Ayah dan ibu keras dalam mengarahkan cita-cita',
        ],
    },
    {
        'kode': 'kebiasaan_belajar',
        'nama': 'Masalah Kebiasaan Belajar',
        'items': [
            'Belajar kalau ada ulangan',
            'Belajar tidak teratur waktunya',
            'Belajar hanya waktu malam hari',
            'Belajar hanya waktu siang hari',
            'Sulit memusatkan perhatian waktu belajar',
            'Sulit mengingat pelajaran yang telah dihafal',
            'Sulit untuk memulai belajar',
            'Kalau belajar sering mengantuk',
            'Sering merasa malas belajar',
            'Sering merasa terganggu saudara ketika belajar',
            'Belajar dengan cara menghafal',
            'Belajar dengan cara membayangkan',
            'Belajar dengan cara membuat ringkasan/singkatan',
            'Tidak dapat menerapkan cara belajar yang baik',
            'Sering menyalin PR teman',
        ],
    },
    {
        'kode': 'muda_mudi_asmara',
        'nama': 'Masalah Muda Mudi dan Asmara',
        'items': [
            'Memikirkan masalah cinta adalah soal yang terlalu awal bagi saya',
            'Berhubungan dengan lawan jenis adalah bagian dari hidup saya',
            'Merasa aneh jika membicarakan soal cinta',
            'Berhubungan dengan lawan jenis dalam masa sekolah dapat menjadi semangat belajar',
            'Berhubungan dengan lawan jenis dalam masa sekolah dapat mengganggu semangat belajar',
            'Saya mulai menyukai teman lawan jenis',
            'Saya lebih tertarik pada teman sejenis',
            'Saya pernah patah hati ditinggal pacar',
            'Sering membayangkan hubungan dengan lawan jenis',
            'Gemar melihat/membaca film cinta',
            'Terpaksa berpacaran secara sembunyi-sembunyi',
            'Merasa jijik/muak jika ada orang membicarakan masalah cinta',
            'Saya tidak bisa belajar jika tidak berkirim surat/chatting',
            'Sering melamun memikirkan si dia/doi',
            'Saya ragu-ragu terhadap pacar saya',
            'Orang tua melarang saya pacaran dulu',
            'Pacar saya selalu mengajak ke luar rumah',
            'Saya kesepian karena belum punya pacar',
            'Iri jika melihat pacaran',
            'Memilih calon pacar sulit bagi saya',
            'Saya menyukai teman, tetapi dia tidak suka (perasaan saya ditolak)',
            'Sulit bergaul dengan teman lawan jenis',
            'Jodoh saya telah ditentukan oleh orang tua',
        ],
    },
]

PCL_ESSAY_QUESTIONS = [
    {'kode': 'masalah_lain', 'pertanyaan': 'Masalah apa yang pernah/sedang kamu hadapi yang belum tercantum di atas?'},
    {'kode': 'masalah_saat_ini', 'pertanyaan': 'Masalah-masalah apa yang sedang kamu hadapi saat ini?'},
    {'kode': 'tempat_curhat', 'pertanyaan': 'Kalau kamu menghadapi masalah yang sulit, dengan siapakah biasanya kamu membicarakannya?'},
]

PCL_PETUNJUK = [
    'Di bawah ini ada beberapa kemungkinan masalah. Pilihlah masalah yang pernah atau sedang kamu alami.',
    'Ananda boleh memilih lebih dari satu dari setiap aspek masalah.',
    'Centang item yang sesuai dengan keadaanmu pada setiap kategori.',
    'Jawablah dengan sejujur dan apa adanya, kamu jangan khawatir atau malu.',
    'Karena hasilnya akan membantu guru bimbingan dan konseling untuk memecahkan masalah-masalah yang kamu hadapi, demi keberhasilan belajar dan masa depanmu.',
]


def pcl_total_items() -> int:
    return sum(len(c['items']) for c in PCL_CATEGORIES)
