/** Pemetaan nama ikon lucide (menu web) → Ionicons (aplikasi). Ikon tak dikenal → ikon umum. */
import type { IconName } from '@/components/ui/Icon';

const MAP: Record<string, IconName> = {
  AlertOctagon: 'warning-outline',
  AlertTriangle: 'alert-circle-outline',
  ArrowRightLeft: 'swap-horizontal-outline',
  Award: 'ribbon-outline',
  BookMarked: 'bookmarks-outline',
  BookOpen: 'book-outline',
  BookOpenCheck: 'reader-outline',
  Briefcase: 'briefcase-outline',
  Building2: 'business-outline',
  Calendar: 'calendar-outline',
  CalendarClock: 'calendar-number-outline',
  CalendarDays: 'calendar-clear-outline',
  CheckCircle2: 'checkmark-circle-outline',
  ClipboardCheck: 'clipboard-outline',
  ClipboardEdit: 'create-outline',
  ClipboardList: 'list-outline',
  ClipboardPlus: 'add-circle-outline',
  Database: 'server-outline',
  DollarSign: 'cash-outline',
  DoorOpen: 'enter-outline',
  FileBarChart: 'bar-chart-outline',
  FileText: 'document-text-outline',
  FileUp: 'cloud-upload-outline',
  Globe: 'globe-outline',
  GraduationCap: 'school-outline',
  Handshake: 'hand-left-outline',
  HeartHandshake: 'heart-outline',
  HeartPulse: 'pulse-outline',
  History: 'time-outline',
  Home: 'home-outline',
  Info: 'information-circle-outline',
  LayoutDashboard: 'grid-outline',
  ListChecks: 'checkbox-outline',
  MapPin: 'location-outline',
  MapPinned: 'map-outline',
  Megaphone: 'megaphone-outline',
  Package: 'cube-outline',
  Pill: 'medkit-outline',
  QrCode: 'qr-code-outline',
  ScanLine: 'scan-outline',
  School: 'library-outline',
  Settings: 'settings-outline',
  ShieldAlert: 'shield-outline',
  ShieldCheck: 'shield-checkmark-outline',
  Sparkles: 'sparkles-outline',
  Stethoscope: 'fitness-outline',
  Syringe: 'bandage-outline',
  Target: 'locate-outline',
  Trash: 'trash-outline',
  Trophy: 'trophy-outline',
  UserCheck: 'person-add-outline',
  UserCircle: 'person-circle-outline',
  UserRoundCog: 'people-circle-outline',
  Users: 'people-outline',
  Wrench: 'construct-outline',
};

export const menuIcon = (name?: string): IconName => (name && MAP[name]) || 'apps-outline';
