/** Label kolom ajuan verval — disalin dari halaman web MyVervalRequestsPage agar sama persis. */
export const PRESTASI_FIELD_LABELS: Record<string, string> = {
  name: 'Nama Lomba',
  bidang_lomba: 'Bidang Lomba',
  category: 'Kategori Lomba',
  level: 'Tingkat Lomba',
  rank: 'Peringkat',
  organizer: 'Nama Penyelenggara',
  date: 'Tanggal Lomba',
  year: 'Tahun',
  academic_year_label: 'Tahun Pelajaran',
  jenis_lomba: 'Jenis Lomba',
  jenis_penyelenggara: 'Jenis Penyelenggara',
  mode_pelaksanaan: 'Mode Pelaksanaan',
  tempat_pelaksanaan: 'Tempat Pelaksanaan',
  cara_mengikuti: 'Diikuti Secara',
  jenis_hadiah: 'Penerimaan Hadiah',
  nama_pembina: 'Nama Pembina',
  description: 'Deskripsi',
  certificate_url: 'Sertifikat',
  photo_url: 'Foto Pemegang Sertifikat/Piala',
};

export const PROFILE_FIELD_LABELS: Record<string, string> = {
  full_name: 'Nama Lengkap',
  nama_tanpa_gelar: 'Nama Tanpa Gelar',
  gelar_depan: 'Gelar Depan',
  gelar_belakang: 'Gelar Belakang',
  email: 'Email',
  phone: 'Nomor Telepon',
  nip_nuptk: 'NIP/NUPTK',
  peg_id: 'Peg ID',
  npk: 'NPK',
  nrg: 'NRG',
  nisn: 'NISN',
  nis: 'NIS',
  gender: 'Jenis Kelamin',
  birth_place: 'Tempat Lahir',
  birth_date: 'Tanggal Lahir',
  status_tempat_tinggal: 'Status Tempat Tinggal',
  provinsi: 'Provinsi',
  kab_kota: 'Kabupaten/Kota',
  kecamatan: 'Kecamatan',
  kelurahan: 'Kelurahan/Desa',
  kode_wilayah: 'Kode Wilayah',
  rt: 'RT',
  rw: 'RW',
  kode_pos: 'Kode Pos',
  address: 'Alamat',
  citizenship: 'Kewarganegaraan',
  nik: 'NIK',
  jumlah_saudara: 'Jumlah Saudara',
  anak_ke: 'Anak Ke-',
  agama: 'Agama',
  cita_cita: 'Cita-cita',
  hobi: 'Hobi',
  pembiaya_sekolah: 'Yang Membiayai Sekolah',
  pra_sekolah: 'Pra-Sekolah',
  imunisasi: 'Imunisasi',
  nomor_kip: 'Nomor KIP',
  nomor_kk: 'Nomor KK',
  nama_kepala_keluarga: 'Nama Kepala Keluarga',
  ayah: 'Data Ayah',
  ibu: 'Data Ibu',
  wali: 'Data Wali',
  alamat_ayah: 'Alamat Ayah',
  alamat_ibu: 'Alamat Ibu',
  alamat_wali: 'Alamat Wali',
  alamat_siswa: 'Alamat Siswa',
  keahlian: 'Keahlian',
  tahfidz: 'Tahfidz',
  beasiswa: 'Beasiswa & Bantuan',
  pendidikan_lain: 'Pendidikan Lain',
  jenis_kebutuhan_khusus: 'Jenis Kebutuhan Khusus',
  kebutuhan_disabilitas: 'Kebutuhan Disabilitas',
  berkas_kartu_keluarga: 'Berkas Kartu Keluarga',
  berkas_akta_kelahiran: 'Berkas Akta Kelahiran',
  berkas_ijazah_sd: 'Berkas Ijazah SD/MI',
  berkas_kip: 'Berkas KIP',
  berkas_pkh: 'Berkas PKH',
  berkas_kks: 'Berkas KKS',
  berkas_kartu_pelajar: 'Berkas Kartu Pelajar',
};

export const HIDDEN_PRESTASI_FIELDS = new Set(['holder_type', 'holder_id', 'holder_name']);

export const requestTypeLabel = (rt?: string) => (rt === 'prestasi_create' ? 'Pengajuan Prestasi' : 'Perubahan Profil');
